#!/usr/bin/env bash
# DistUpgradeConfigParser ASCII-only config gate (Xenial→Bionic).
# Reproduces Bionic UpgradeTool UnicodeDecodeError under LC_ALL=C and verifies
# client fail-closed pre-DRO validation. No real do-release-upgrade transaction.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT_IN="${ROOT}/client/dp-offline-upgrade-xenial-to-bionic.sh.in"
UPGRADER_TAR="${TEST_UPGRADER_TAR:-/var/spool/apt-mirror/selective/current/shared/offline/release-upgraders/bionic/bionic.tar.gz}"
FAIL=0
pass() { echo "  PASS: $*"; }
fail() { echo "  FAIL: $*"; FAIL=1; }

WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

echo "=== test_distupgrade_config_ascii ==="

[[ -f "$SCRIPT_IN" ]] || { echo "missing template"; exit 1; }

# ---------------------------------------------------------------------------
# Locate exact non-ASCII generator strings (historical failure: U+2192 arrow)
# ---------------------------------------------------------------------------
python3 - <<'PY' || fail "generator still embeds non-ASCII into DistUpgrade cfg heredocs"
from pathlib import Path
text = Path("/home/aella/ubuntu-mirror-automation/client/dp-offline-upgrade-xenial-to-bionic.sh.in").read_text(encoding="utf-8")
# Extract apply_distupgrade_mirror_override body
start = text.index("apply_distupgrade_mirror_override()")
end = text.index("\ninstall_effective_source_gate()", start)
body = text[start:end]
# The cfg/mirrors heredoc payloads must be ASCII-only.
import re
for m in re.finditer(r"cat >\"\$\{(mirrors_path|cfg_path)\}\.new\" <<EOF\n(.*?)EOF", body, re.S):
    payload = m.group(2)
    raw = payload.encode("utf-8")
    bad = [i for i,b in enumerate(raw) if b >= 0x80]
    if bad:
        raise SystemExit("non-ascii in %s heredoc at offset %d" % (m.group(1), bad[0]))
print("GENERATOR_ASCII_OK")
PY
grep -q 'Xenial-to-Bionic' "$SCRIPT_IN" \
  && pass "3/15 generator uses ASCII Xenial-to-Bionic label" \
  || fail "ASCII hop label missing in generator"
if grep -nE 'Xenial→Bionic|— DistUpgrade|ValidMirrors overlay \(Xenial→' "$SCRIPT_IN" \
  | grep -E 'mirrors_path|cfg_path|Generated by stellar|ValidMirrors overlay'; then
  fail "cfg/mirrors generator still has non-ASCII"
else
  pass "cfg/mirrors generator heredocs free of arrow/em-dash"
fi

# ---------------------------------------------------------------------------
# Extract DistUpgradeConfigParser from Bionic UpgradeTool
# ---------------------------------------------------------------------------
PARSER_DIR="${WORKDIR}/upgrader"
mkdir -p "$PARSER_DIR"
if [[ -f "$UPGRADER_TAR" ]]; then
  tar -xzf "$UPGRADER_TAR" -C "$PARSER_DIR" \
    ./DistUpgradeConfigParser.py ./DistUpgrade.cfg ./DistUpgrade.cfg.xenial ./mirrors.cfg
  pass "extracted Bionic DistUpgradeConfigParser"
else
  fail "upgrader tar missing: $UPGRADER_TAR"
fi

# Fake lsb_release -> xenial so DistUpgrade.cfg.xenial is selected when present
FAKEBIN="${WORKDIR}/fakebin"
mkdir -p "$FAKEBIN"
cat >"${FAKEBIN}/lsb_release" <<'EOF'
#!/bin/sh
if [ "$1" = "-c" ] && [ "$2" = "-s" ]; then echo xenial; exit 0; fi
echo "lsb_release stub"; exit 0
EOF
chmod 0755 "${FAKEBIN}/lsb_release"
export PATH="${FAKEBIN}:$PATH"

# ---------------------------------------------------------------------------
# 1/2) Reproduce UnicodeDecodeError with em-dash / arrow in override cfg
# ---------------------------------------------------------------------------
OV_BAD="${WORKDIR}/override-bad"
mkdir -p "$OV_BAD"
# Exact historical failure shape: Unicode arrow at byte offset 37 on line 1
printf '%s\n' '# Generated by stellar offline Xenial→Bionic client.' \
  '# DistUpgradeConfig reads release-upgrades.d/*.cfg after DistUpgrade.cfg.xenial.' \
  '[Sources]' \
  'AllowThirdParty=yes' >"${OV_BAD}/99-stellar-offline-mirror.cfg"

python3 - <<PY
from pathlib import Path
raw = Path("${OV_BAD}/99-stellar-offline-mirror.cfg").read_bytes()
assert raw[37] == 0xE2, hex(raw[37])
assert raw[37:40] == bytes.fromhex("e28692")
line = raw.splitlines()[0].decode("utf-8")
print("DISTUPGRADE_CONFIG_NONASCII_FILE=${OV_BAD}/99-stellar-offline-mirror.cfg")
print("DISTUPGRADE_CONFIG_NONASCII_LINE=1")
print("DISTUPGRADE_CONFIG_NONASCII_COLUMN=38")
print("DISTUPGRADE_CONFIG_NONASCII_CODEPOINT=U+2192")
print("DISTUPGRADE_CONFIG_NONASCII_UTF8=E2 86 92")
print("DISTUPGRADE_CONFIG_NONASCII_TEXT=" + line)
PY

# Python 3.12 defaults to UTF-8 mode; force locale encoding like Xenial 3.5.
run_distupgrade_config() {
  local ov="$1"
  ( cd "$PARSER_DIR" && \
    LC_ALL=C LANG=C PYTHONUTF8=0 python3 - "$ov" <<'PY'
from DistUpgradeConfigParser import DistUpgradeConfig
import sys
c = DistUpgradeConfig(".", override_dir=sys.argv[1])
print("CONFIG_FILES=" + ",".join(c.config_files))
if c.has_option("Sources", "AllowThirdParty"):
    print("ALLOW=" + c.get("Sources", "AllowThirdParty"))
print("DISTUPGRADE_CONFIG_INIT=PASS")
PY
  )
}

set +e
out="$(run_distupgrade_config "$OV_BAD" 2>&1)"
rc=$?
set -e
if [[ "$rc" -ne 0 ]] && printf '%s' "$out" | grep -q 'UnicodeDecodeError' \
  && printf '%s' "$out" | grep -q '0xe2'; then
  pass "1 actual DistUpgradeConfig reproduces UnicodeDecodeError on arrow cfg"
else
  fail "1 expected UnicodeDecodeError reproduction (rc=${rc})"
  printf '%s\n' "$out" | tail -30
fi

# Also em dash (U+2014) variant
OV_EM="${WORKDIR}/override-em"
mkdir -p "$OV_EM"
printf '# Stellar offline mirror — DistUpgrade override\n[Sources]\nAllowThirdParty=yes\n' \
  >"${OV_EM}/99-bad.cfg"
set +e
out="$(run_distupgrade_config "$OV_EM" 2>&1)"
rc=$?
set -e
if [[ "$rc" -ne 0 ]] && printf '%s' "$out" | grep -q 'UnicodeDecodeError'; then
  pass "1b em dash cfg also UnicodeDecodeError under LC_ALL=C/PYTHONUTF8=0"
else
  fail "1b em dash reproduction failed"
  printf '%s\n' "$out" | tail -20
fi

# ---------------------------------------------------------------------------
# 4) ASCII-only configs → DistUpgradeConfig PASS
# ---------------------------------------------------------------------------
OV_OK="${WORKDIR}/override-ok"
mkdir -p "$OV_OK"
printf '%s\n' \
  '# Generated by stellar offline Xenial-to-Bionic client.' \
  '# DistUpgradeConfig reads release-upgrades.d/*.cfg after DistUpgrade.cfg.xenial.' \
  '[Sources]' \
  'AllowThirdParty=yes' >"${OV_OK}/99-stellar-offline-mirror.cfg"
set +e
out="$(run_distupgrade_config "$OV_OK" 2>&1)"
rc=$?
set -e
if [[ "$rc" -eq 0 ]] && printf '%s' "$out" | grep -q 'ALLOW=yes'; then
  pass "4 LC_ALL=C DistUpgradeConfig init PASS on ASCII override"
  printf '%s\n' "$out" | grep '^CONFIG_FILES=' || true
else
  fail "4 ASCII DistUpgradeConfig init failed"
  printf '%s\n' "$out" | tail -20
fi

# ---------------------------------------------------------------------------
# Client gate helper extraction
# ---------------------------------------------------------------------------
GATE_SH="${WORKDIR}/gate-harness.sh"
SCRIPT_IN="$SCRIPT_IN" GATE_SH="$GATE_SH" python3 - <<'PY'
from pathlib import Path
import os
script_in = os.environ["SCRIPT_IN"]
gate_sh = os.environ["GATE_SH"]
text = Path(script_in).read_text(encoding="utf-8")
idx = text.index("validate_distupgrade_config_ascii_before_dro()")
end = text.index("\nvalidate_meta_release_before_dro()", idx)
body = text[idx:end]
hdr = r'''#!/usr/bin/env bash
set -eo pipefail
TEST_ROOT="${STELLAR_OFFLINE_TEST_ROOT:-}"
_TEST_PREFIX="$TEST_ROOT"
_hp() {
  if [[ -n "$_TEST_PREFIX" ]]; then printf '%s%s' "$_TEST_PREFIX" "$1"; else printf '%s' "$1"; fi
}
log() { local level="$1"; shift; printf '%s [%s] %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$level" "$*" >&2; }
die() { local code="$1"; shift; log ERROR "$* (exit=${code})"; exit "$code"; }
fail_stage() { local rc="$1"; shift; log ERROR "FAIL_STAGE $* FAILURE_CLASS=${FAILURE_CLASS:-}"; exit "$rc"; }
FAILURE_CLASS=""
DISTUPGRADE_OVERRIDE_DIR="/etc/update-manager/release-upgrades.d"
DISTUPGRADE_OVERRIDE_CFG="${DISTUPGRADE_OVERRIDE_DIR}/99-stellar-offline-mirror.cfg"
DISTUPGRADE_MIRRORS_FILE="/opt/aelladata/os-upgrade/offline/distupgrade-valid-mirrors.cfg"
'''
Path(gate_sh).write_text(hdr + body + "\n")
print("harness_bytes", Path(gate_sh).stat().st_size)
PY
bash -n "$GATE_SH" && pass "gate harness bash -n" || fail "gate harness bash -n"

run_gate() {
  local root="$1"
  env -i PATH="/usr/bin:/bin" HOME=/tmp \
    STELLAR_OFFLINE_TEST_ROOT="$root" \
    /bin/bash -c "source '$GATE_SH'; validate_distupgrade_config_ascii_before_dro" 2>"$root/gate.err"
}

setup_ascii_root() {
  local root="$1"
  mkdir -p "$root/etc/update-manager/release-upgrades.d" \
    "$root/opt/aelladata/os-upgrade/offline"
  printf '# stellar offline DistUpgrade ValidMirrors overlay (Xenial-to-Bionic)\nhttp://archive.ubuntu.com/ubuntu/\nhttp://example.invalid/hops/xenial-to-bionic/ubuntu\nhttp://example.invalid/hops/xenial-to-bionic/ubuntu/\n' \
    >"$root/opt/aelladata/os-upgrade/offline/distupgrade-valid-mirrors.cfg"
  printf '# Generated by stellar offline Xenial-to-Bionic client.\n[Sources]\nValidMirrors=%s\nAllowThirdParty=yes\n' \
    "$root/opt/aelladata/os-upgrade/offline/distupgrade-valid-mirrors.cfg" \
    >"$root/etc/update-manager/release-upgrades.d/99-stellar-offline-mirror.cfg"
}

# 13/14/15/16 ASCII comment + local mirror URI PASS
R_OK="${WORKDIR}/root-ok"
setup_ascii_root "$R_OK"
set +e
run_gate "$R_OK"
rc=$?
set -e
if [[ "$rc" -eq 0 ]] && grep -q 'DISTUPGRADE_CONFIG_ASCII_VALIDATION=PASS' "$R_OK/gate.err"; then
  pass "13/14/15/16 ASCII override+ValidMirrors gate PASS"
else
  fail "ASCII gate should PASS"
  cat "$R_OK/gate.err" || true
fi

# Helper to inject bad byte sequence into override cfg
inject_cfg() {
  local root="$1"
  local label="$2"
  local raw_hex="$3"
  setup_ascii_root "$root"
  python3 - "$root" "$raw_hex" <<'PY'
import sys, binascii
root, hx = sys.argv[1], sys.argv[2]
path = root + "/etc/update-manager/release-upgrades.d/99-stellar-offline-mirror.cfg"
seq = binascii.unhexlify(hx.replace(" ", ""))
open(path, "wb").write(b"# bad " + seq + b" comment\n[Sources]\nAllowThirdParty=yes\n")
PY
}

expect_nonascii() {
  local root="$1"
  local label="$2"
  set +e
  run_gate "$root"
  rc=$?
  set -e
  if [[ "$rc" -ne 0 ]] && grep -q 'FAIL_DISTUPGRADE_CONFIG_NONASCII' "$root/gate.err"; then
    pass "$label -> FAIL_DISTUPGRADE_CONFIG_NONASCII"
  else
    fail "$label expected NONASCII fail"
    cat "$root/gate.err" || true
  fi
}

# 6 em dash U+2014 E2 80 94
R="${WORKDIR}/em"; inject_cfg "$R" em "e28094"; expect_nonascii "$R" "6 em dash"
# 7 en dash U+2013 E2 80 93
R="${WORKDIR}/en"; inject_cfg "$R" en "e28093"; expect_nonascii "$R" "7 en dash"
# 8 smart quote U+201C E2 80 9C
R="${WORKDIR}/sq"; inject_cfg "$R" sq "e2809c"; expect_nonascii "$R" "8 smart quote"
# 9 arrow U+2192 E2 86 92
R="${WORKDIR}/ar"; inject_cfg "$R" ar "e28692"; expect_nonascii "$R" "9 unicode arrow"
# 10 NBSP U+00A0 C2 A0
R="${WORKDIR}/nb"; inject_cfg "$R" nb "c2a0"; expect_nonascii "$R" "10 NBSP"

# 11 BOM
R="${WORKDIR}/bom"
setup_ascii_root "$R"
python3 - "$R" <<'PY'
import sys
root=sys.argv[1]
path=root+"/etc/update-manager/release-upgrades.d/99-stellar-offline-mirror.cfg"
body=open(path,"rb").read()
open(path,"wb").write(b"\xef\xbb\xbf"+body)
PY
set +e
run_gate "$R"
rc=$?
set -e
if [[ "$rc" -ne 0 ]] && grep -q 'FAIL_DISTUPGRADE_CONFIG_BOM' "$R/gate.err"; then
  pass "11 UTF-8 BOM -> FAIL_DISTUPGRADE_CONFIG_BOM"
else
  fail "11 BOM should fail"
  cat "$R/gate.err" || true
fi

# 12 missing/unreadable
R="${WORKDIR}/miss"
mkdir -p "$R/etc/update-manager/release-upgrades.d" "$R/opt/aelladata/os-upgrade/offline"
# override dir exists but cfg missing
set +e
run_gate "$R"
rc=$?
set -e
if [[ "$rc" -ne 0 ]] && grep -q 'FAIL_DISTUPGRADE_CONFIG_UNREADABLE' "$R/gate.err"; then
  pass "12 missing cfg -> FAIL_DISTUPGRADE_CONFIG_UNREADABLE"
else
  fail "12 missing should be UNREADABLE"
  cat "$R/gate.err" || true
fi

# 17 failure classification
python3 - <<'PY' || fail "17 classify_dro_failure missing DISTUPGRADE_CONFIG_TEXT_ENCODING"
from pathlib import Path
text = Path("/home/aella/ubuntu-mirror-automation/client/dp-offline-upgrade-xenial-to-bionic.sh.in").read_text(encoding="utf-8")
assert "FAILURE_CLASS=\"DISTUPGRADE_CONFIG_TEXT_ENCODING\"" in text or 'FAILURE_CLASS="DISTUPGRADE_CONFIG_TEXT_ENCODING"' in text
assert "DistUpgradeConfigParser" in text
assert "DISTUPGRADE_CONFIG_PARSER_STAGE=INITIALIZATION" in text
print("CLASSIFICATION_MARKERS_OK")
PY
pass "17 config encoding failure classification markers present"

# ---------------------------------------------------------------------------
# Bionic→Focal template: same ASCII generator / classification invariants
# ---------------------------------------------------------------------------
B2F_IN="${ROOT}/client/dp-offline-upgrade-bionic-to-focal.sh.in"
if [[ -f "$B2F_IN" ]]; then
  python3 - "$B2F_IN" <<'PY' || fail "b2f generator still embeds non-ASCII into DistUpgrade cfg heredocs"
import re, sys
from pathlib import Path
text = Path(sys.argv[1]).read_text(encoding="utf-8")
start = text.index("apply_distupgrade_mirror_override()")
end = text.index("\ninstall_effective_source_gate()", start)
body = text[start:end]
for m in re.finditer(r"cat >\"\$\{(mirrors_path|cfg_path)\}\.new\" <<EOF\n(.*?)EOF", body, re.S):
    payload = m.group(2)
    raw = payload.encode("utf-8")
    bad = [i for i,b in enumerate(raw) if b >= 0x80]
    if bad:
        raise SystemExit("non-ascii in %s heredoc at offset %d" % (m.group(1), bad[0]))
print("B2F_GENERATOR_ASCII_OK")
PY
  grep -q 'Bionic-to-Focal' "$B2F_IN" \
    && pass "b2f generator uses ASCII Bionic-to-Focal label" \
    || fail "b2f ASCII hop label missing"
  python3 - "$B2F_IN" <<'PY' || fail "b2f classify_dro_failure missing DISTUPGRADE_CONFIG_TEXT_ENCODING"
from pathlib import Path
import sys
text = Path(sys.argv[1]).read_text(encoding="utf-8")
assert "FAILURE_CLASS=\"DISTUPGRADE_CONFIG_TEXT_ENCODING\"" in text or 'FAILURE_CLASS="DISTUPGRADE_CONFIG_TEXT_ENCODING"' in text
assert "DistUpgradeConfigParser" in text
print("B2F_CLASSIFICATION_MARKERS_OK")
PY
  LC_ALL=C LANG=C bash -n "$B2F_IN" && pass "b2f template bash -n under LC_ALL=C" || fail "b2f bash -n"
else
  fail "b2f template missing"
fi

# 5 smoke: client template bash -n + gate under LC_ALL=C
LC_ALL=C LANG=C bash -n "$SCRIPT_IN" && pass "5/28 template bash -n under LC_ALL=C" || fail "bash -n"

# Report DistUpgradeConfig.config_files ordering from ASCII run
out="$(run_distupgrade_config "$OV_OK" 2>&1)" || true
printf '%s\n' "$out" | grep '^CONFIG_FILES=' || true
echo "DISTUPGRADE_CONFIG_FILES_ORDERED (datadir then release-upgrades.d/*.cfg):"
printf '%s\n' "$out" | sed -n 's/^CONFIG_FILES=//p' | tr ',' '\n' | sed 's/^/  /'

if [[ "$FAIL" -ne 0 ]]; then
  echo "RESULT: FAIL"
  exit 1
fi
echo "RESULT: PASS"
exit 0
